name: deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to firebase
        shell: bash
        env:
          FIREBASE_SA_KEY: ${{ secrets.FIREBASE_SA_KEY }}
        run: ./deploy.sh
